namespace MIF.Modules.Todos.Domain;

// <auto-generated />
// This file represents scaffolded database shape.
// Re-generate from the database when schema changes.
public partial class TodoItem
{
    public string Title { get; set; } = string.Empty;

    public bool IsCompleted { get; set; }
}
