namespace MIF.Modules.Todos.Domain;

// <auto-generated />
// This file represents scaffolded database shape.
// Re-generate from the database when schema changes.
public partial class TodoItem
{
    public int Id { get; set; }

    public string Title { get; set; } = string.Empty;

    public bool IsCompleted { get; set; }

    public string? AssignedTo { get; set; } = string.Empty;

    public Importance Importance { get; set; } = Importance.Medium;
}
